'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type RequestRow = { id: string; job_number: string; branch_id: string; category: string; priority: string; status: string; problem_description: string; reported_by: string | null; reported_at: string; branches?: { branch_name: string; branch_code: string }[] | null }

export default function BranchRequestsPage() {
  const supabase = createClient(); const [rows, setRows] = useState<RequestRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState('')
  useEffect(() => { async function load() { const { data, error } = await supabase.from('maintenance_jobs').select('id, job_number, branch_id, category, priority, status, problem_description, reported_by, reported_at, branches(branch_name, branch_code)').in('status', ['NEW','UNDER REVIEW','ASSIGNED']).order('reported_at', { ascending: false }); if (error) setError(error.message); setRows((data ?? []) as unknown as RequestRow[]); setLoading(false) } load() }, [])
  const filtered = useMemo(() => rows.filter((r) => { const q=search.toLowerCase(); return (!q || `${r.job_number} ${r.problem_description} ${r.category} ${r.branches?.[0]?.branch_name ?? ''}`.toLowerCase().includes(q)) && (!status || r.status === status) }), [rows,search,status])
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-sm font-semibold uppercase tracking-wider text-[#e85d91]">Branches</div><h1 className="mt-1 text-3xl font-black text-[#4a2633]">Branch Requests</h1><p className="mt-2 text-sm text-slate-500">Review maintenance requests awaiting HQ action or contractor assignment.</p></div><Link href="/jobs/new" className="rounded-xl bg-[#f582ae] px-4 py-3 text-sm font-bold text-white">+ Create Job</Link></div>
    <div className="dunkin-card p-4 flex flex-col gap-3 md:flex-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Job, branch, category or problem..." className="flex-1 rounded-xl border border-[#ead4dd] px-4 py-3 text-sm outline-none"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#ead4dd] px-4 py-3 text-sm"><option value="">All Request Statuses</option><option>NEW</option><option>UNDER REVIEW</option><option>ASSIGNED</option></select></div>
    {error && <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="grid gap-4 md:grid-cols-3"><div className="dunkin-card p-5"><div className="text-sm text-slate-500">Requests</div><div className="mt-2 text-3xl font-black text-[#4a2633]">{filtered.length}</div></div><div className="dunkin-card p-5"><div className="text-sm text-slate-500">Critical</div><div className="mt-2 text-3xl font-black text-red-600">{filtered.filter(r=>r.priority==='CRITICAL').length}</div></div><div className="dunkin-card p-5"><div className="text-sm text-slate-500">New</div><div className="mt-2 text-3xl font-black text-[#e85d91]">{filtered.filter(r=>r.status==='NEW').length}</div></div></div>
    <div className="space-y-3">{loading ? <div className="dunkin-card p-6 text-sm text-slate-500">Loading...</div> : filtered.length===0 ? <div className="dunkin-card p-6 text-sm text-slate-500">No branch requests found.</div> : filtered.map(r=><Link key={r.id} href={`/jobs/${r.id}`} className="block dunkin-card p-5 hover:border-[#f582ae]"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><div className="flex flex-wrap items-center gap-2"><span className="font-black text-[#4a2633]">{r.job_number}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{r.status}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.priority==='CRITICAL'?'bg-red-100 text-red-700':'bg-orange-100 text-orange-700'}`}>{r.priority}</span></div><h2 className="mt-2 font-bold text-slate-800">{r.problem_description}</h2><p className="mt-1 text-sm text-slate-500">{r.branches?.[0]?.branch_code} · {r.branches?.[0]?.branch_name} · {r.category}</p></div><div className="text-sm text-slate-500">{new Date(r.reported_at).toLocaleString('en-MY')}</div></div></Link>)}</div>
  </div>
}
